'use client';
import { useState } from 'react';

const FAQS = [
  {
    q: 'Do I need a Shopify store to use Ephermal?',
    a: 'Ephermal connects directly to your Shopify store via OAuth — no app store required. You install by authorising access from inside your Ephermal dashboard. Your products, pricing and store data sync instantly.',
  },
  {
    q: 'How does the UGC ad generation work?',
    a: 'Our AI analyses your products and brand, then uses the Ephermal UGC Engine to generate authentic creator-style video and image ads. These are real UGC-style creatives — not templates or stock footage. You review and approve before anything goes live.',
  },
  {
    q: 'Which ad platforms does Ephermal support?',
    a: 'Ephermal fully supports Meta Ads — including Facebook and Instagram Feed, Stories, and Reels. Campaigns are created and managed via Meta\'s official Ads API. Everything runs from a single dashboard.',
  },
  {
    q: 'Can I approve creatives before they launch?',
    a: 'Yes — every creative generated by Ephermal goes through your approval queue first. You can approve, reject, or request a regeneration before anything is published to your ad accounts. You stay in full control.',
  },
  {
    q: 'What happens if my ad underperforms?',
    a: "Ephermal's closed-loop optimization automatically detects underperforming ads and regenerates new creatives to replace them. It learns what works for your store over time and compounds performance — the longer you run it, the smarter it gets.",
  },
  {
    q: 'How is billing handled?',
    a: 'Billing is handled directly through Ephermal — separate from your Shopify billing. You subscribe monthly and can cancel any time from your dashboard. No agency fees, no hidden costs.',
  },
  {
    q: 'What are UGC credits?',
    a: 'Each plan includes a monthly UGC credit allocation. One credit generates one UGC creative (video or image). If you need more than your plan includes, you can purchase additional credit packs from within your dashboard at any time.',
  },
];

export default function FAQ() {
  const [open, setOpen] = useState<number | null>(null);

  return (
    <section className="section faq-section" id="faq" style={{ paddingTop: '80px', paddingBottom: '100px' }}>
      <div className="container">
        <div style={{ textAlign: 'center', marginBottom: '64px' }}>
          <div className="section-label" data-reveal>FAQ</div>
          <h2 className="section-title" data-reveal data-delay="1">Common questions</h2>
        </div>
        <div className="faq-list">
          {FAQS.map((f, i) => (
            <div
              key={i}
              className={`faq-item${open === i ? ' open' : ''}`}
            >
              <div className="faq-q" onClick={() => setOpen(open === i ? null : i)}>
                <span>{f.q}</span>
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <polyline points="6 9 12 15 18 9" />
                </svg>
              </div>
              <div className="faq-a">{f.a}</div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
