'use client';
import { useState } from 'react';

const FAQS = [
  {
    q: 'Do I need any ad experience to use Ephermal?',
    a: 'No experience required. Ephermal is built specifically for Shopify store owners who have never run a paid ad in their life. You connect your store, and the AI handles audience research, creative writing, campaign setup, and budget management. You review and approve. That\'s it.',
  },
  {
    q: 'My store is very new. Can I still use Ephermal?',
    a: 'Ephermal is designed for stores at the earliest stage. Whether you\'ve made 10 sales or 10,000, the AI reads your catalog and builds a campaign strategy around what you actually have. The sooner you start running real ads, the sooner you find out what the market wants.',
  },
  {
    q: 'How much should I spend on ads to start?',
    a: 'You set your own ad budget. Ephermal never charges against your ad spend. Most early-stage stores start with $10–$30/day on Meta to test what converts. Ephermal\'s job is to make every dollar of that spend smarter: better audiences, better creatives, better signals on what to scale.',
  },
  {
    q: 'Do I need a Shopify store to use Ephermal?',
    a: 'Yes. Ephermal connects directly to your Shopify store via OAuth. You authorise access from inside your Ephermal dashboard in about 90 seconds. Your products, pricing, inventory and store data sync instantly and stay live.',
  },
  {
    q: 'Which ad platforms does Ephermal support?',
    a: 'All plans include Meta Ads automation (Facebook and Instagram Feed, Stories, and Reels) via the official Meta Marketing API. Growth and Scale plans also unlock Google Ads, including Search, Shopping, Performance Max, and YouTube, via the Google Ads API. Everything is managed from one dashboard.',
  },
  {
    q: 'How does the AI content engine work?',
    a: 'Ephermal reads your live product catalog and generates creator-style ad scripts, hooks, headlines, and copy tailored to your actual products. These are not templates. Every brief is written specifically for your store and audience. You review and approve before anything goes live.',
  },
  {
    q: 'Can I approve creatives before they launch?',
    a: 'Yes. Every creative generated by Ephermal goes through your approval queue first. You can approve, reject, or request a regeneration before anything is published to your ad accounts. You stay in full control at all times.',
  },
  {
    q: 'What is Competitor Radar?',
    a: 'Competitor Radar searches the Meta Ad Library for active ads in your niche. You enter a keyword or brand name and it surfaces what competitors are running right now. The AI then breaks down the hook type, target emotion, and CTA, then writes a counter-strategy so you can position against them before you spend a dollar.',
  },
  {
    q: 'How does profit-aware campaign optimisation work?',
    a: "Enter your cost of goods (COGS) for each product and Ephermal shifts its entire campaign strategy to optimise for net profit, not just revenue or ROAS. A 5× ROAS on a 10% margin product is less profitable than 2× on a 70% margin product. Profit Tracker makes that visible and Ephermal acts on it automatically.",
  },
  {
    q: 'How is billing handled?',
    a: 'Billing is handled directly through Ephermal via Stripe, separate from your Shopify billing. You subscribe monthly and can cancel any time from your dashboard. No agency fees, no hidden costs, no minimum contract.',
  },
];

export default function FAQ() {
  const [open, setOpen] = useState<number | null>(null);

  return (
    <section className="section faq-section" id="faq" style={{ paddingTop: '80px', paddingBottom: '100px' }}>
      <div className="container">
        <div style={{ textAlign: 'center', marginBottom: '64px' }}>
          <div className="section-label" data-reveal>FAQ</div>
          <h2 className="section-title" data-reveal data-delay="1">Common questions</h2>
        </div>
        <div className="faq-list">
          {FAQS.map((f, i) => (
            <div
              key={i}
              className={`faq-item${open === i ? ' open' : ''}`}
            >
              <div className="faq-q" onClick={() => setOpen(open === i ? null : i)}>
                <span>{f.q}</span>
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <polyline points="6 9 12 15 18 9" />
                </svg>
              </div>
              <div className="faq-a">{f.a}</div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
