'use client';
import { useState } from 'react';

const FAQS = [
  {
    q: 'Do I need a Shopify store to use Ephermal?',
    a: 'Yes — Ephermal connects directly to your Shopify store via OAuth. You authorise access from inside your Ephermal dashboard in about 90 seconds. Your products, pricing, inventory and store data sync instantly and stay live.',
  },
  {
    q: 'Which ad platforms does Ephermal support?',
    a: 'All plans include Meta Ads automation (Facebook and Instagram Feed, Stories, and Reels) via the official Meta Marketing API. Growth and Scale plans also unlock Google Ads — including Search, Shopping, Performance Max, and YouTube — via the Google Ads API. Everything is managed from one dashboard.',
  },
  {
    q: 'How does the AI content engine work?',
    a: 'Ephermal reads your live product catalog and generates creator-style ad scripts, hooks, headlines, and copy tailored to your actual products. These are not templates — every brief is written specifically for your store and audience. You review and approve before anything goes live.',
  },
  {
    q: 'Can I approve creatives before they launch?',
    a: 'Yes — every creative generated by Ephermal goes through your approval queue first. You can approve, reject, or request a regeneration before anything is published to your ad accounts. You stay in full control at all times.',
  },
  {
    q: 'What is Competitor Radar?',
    a: 'Competitor Radar searches the Meta Ad Library for active ads in your niche. You enter a keyword or brand name and it surfaces what competitors are running right now. The AI then breaks down the hook type, target emotion, and CTA — and writes a counter-strategy so you can position against them before you spend a dollar.',
  },
  {
    q: 'What is Creative Brief AI?',
    a: 'Creative Brief AI generates a full ad creative strategy from your live product catalog and recent campaign history. It produces hook angles, copy variations, format recommendations, and target audience profiles in seconds. Briefs are saved to your dashboard and can be regenerated any time your catalog changes.',
  },
  {
    q: 'How does profit-aware campaign optimisation work?',
    a: "Enter your cost of goods (COGS) for each product and Ephermal shifts its entire campaign strategy to optimise for net profit, not just revenue or ROAS. A 5× ROAS on a 10% margin product is less profitable than 2× on a 70% margin product. Profit Tracker makes that visible and Ephermal acts on it automatically.",
  },
  {
    q: 'What are UGC credits?',
    a: 'Each plan includes a monthly UGC credit allocation. One credit generates one AI content asset — a script, headline set, or copy variation. If you need more than your plan includes, you can purchase additional credit packs from inside your dashboard at any time.',
  },
  {
    q: 'How is billing handled?',
    a: 'Billing is handled directly through Ephermal via Stripe — separate from your Shopify billing. You subscribe monthly and can cancel any time from your dashboard. No agency fees, no hidden costs, no minimum contract.',
  },
];

export default function FAQ() {
  const [open, setOpen] = useState<number | null>(null);

  return (
    <section className="section faq-section" id="faq" style={{ paddingTop: '80px', paddingBottom: '100px' }}>
      <div className="container">
        <div style={{ textAlign: 'center', marginBottom: '64px' }}>
          <div className="section-label" data-reveal>FAQ</div>
          <h2 className="section-title" data-reveal data-delay="1">Common questions</h2>
        </div>
        <div className="faq-list">
          {FAQS.map((f, i) => (
            <div
              key={i}
              className={`faq-item${open === i ? ' open' : ''}`}
            >
              <div className="faq-q" onClick={() => setOpen(open === i ? null : i)}>
                <span>{f.q}</span>
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <polyline points="6 9 12 15 18 9" />
                </svg>
              </div>
              <div className="faq-a">{f.a}</div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
