-- Migration 019: Store Intelligence
-- ─────────────────────────────────────────────────────────────────────────────
-- Permanent brand-context brief per user, generated by Claude Sonnet from the
-- user's connected Shopify store data. Referenced by ad copy, UGC scripts, and
-- Higgsfield/Riverflow creative prompts so every AI output is store-specific.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS store_intelligence (
  user_id           TEXT        PRIMARY KEY,
  shop              TEXT        NOT NULL,
  summary           TEXT,
  target_audience   TEXT,
  ad_opportunities  TEXT,
  meta_strategy     TEXT,
  products          JSONB       DEFAULT '[]',
  keywords          TEXT[]      DEFAULT '{}',
  brand_vibe        TEXT,
  color_palette     JSONB       DEFAULT '{}',   -- {primary, secondary, accent, background, text_on_bg}
  typography        JSONB       DEFAULT '{}',   -- {heading_style, body_style}
  ugc_visual        TEXT,
  ugc_tone          TEXT,
  logo_url          TEXT,
  model_version     TEXT,
  generated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE store_intelligence ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users see own store intelligence"
  ON store_intelligence FOR SELECT
  USING (user_id = auth.jwt()->>'sub');

-- Writes happen only via Edge Function (service_role bypasses RLS).
REVOKE INSERT, UPDATE, DELETE ON store_intelligence FROM authenticated;
